from google import genai
from google.genai import types
import mss
import io
from PIL import Image
from dotenv import load_dotenv
import os

# Load environment variables from .env file
load_dotenv()


def get_snarky_comment() -> str:
    """
    Takes a screenshot of the primary monitor and returns a snarky comment
    based on what's visible in the screenshot.

    Returns:
        str: A snarky comment generated by Gemini about the screenshot
    """
    try:
        # Capture screenshot
        with mss.mss() as sct:
            monitor = sct.monitors[1]  # Primary monitor
            screenshot = sct.grab(monitor)

            # Convert to PIL Image
            img = Image.frombytes(
                "RGB", screenshot.size, screenshot.bgra, "raw", "BGRX"
            )

            # Convert to bytes for Gemini
            img_byte_arr = io.BytesIO()
            img.save(img_byte_arr, format="PNG")
            img_bytes = img_byte_arr.getvalue()

        # Create image part for Gemini
        image = types.Part.from_bytes(data=img_bytes, mime_type="image/png")

        # Initialize Gemini client with API key from environment
        api_key = os.getenv("GOOGLE_API_KEY")
        if not api_key:
            return "Error: GOOGLE_API_KEY not found in environment variables"

        client = genai.Client(api_key=api_key)

        print("Sending request to Gemini...")
        response = client.models.generate_content(
            model="gemini-2.0-flash-exp",
            contents=[
                "Give me a short snarky comment about this image. Less than 20 words.",
                image,
            ],
        )

        print(f"Response received. Type: {type(response)}")
        print(f"Response attributes: {dir(response)}")
        print(f"Response.text: {response.text}")

        if response.text:
            return response.text
        else:
            return "Response was empty - API key might not be configured"

    except Exception as e:
        print(f"Exception in get_snarky_comment: {type(e).__name__}: {e}")
        import traceback

        traceback.print_exc()
        return f"Error: {e}"


if __name__ == "__main__":
    # Test the function
    comment = get_snarky_comment()
    print(comment)
