from google import genai
from google.genai import types
import mss
import io
from PIL import Image


def get_snarky_comment() -> str:
    """
    Takes a screenshot of the primary monitor and returns a snarky comment
    based on what's visible in the screenshot.

    Returns:
        str: A snarky comment generated by Gemini about the screenshot
    """
    # Capture screenshot
    with mss.mss() as sct:
        monitor = sct.monitors[1]  # Primary monitor
        screenshot = sct.grab(monitor)

        # Convert to PIL Image
        img = Image.frombytes("RGB", screenshot.size, screenshot.bgra, "raw", "BGRX")

        # Convert to bytes for Gemini
        img_byte_arr = io.BytesIO()
        img.save(img_byte_arr, format="PNG")
        img_bytes = img_byte_arr.getvalue()

    # Create image part for Gemini
    image = types.Part.from_bytes(data=img_bytes, mime_type="image/png")

    # Initialize Gemini client
    client = genai.Client()

    response = client.models.generate_content(
        model="gemini-3-flash-preview",
        contents=["Give me a short snarky comment about this image:", image],
    )

    return response.text


if __name__ == "__main__":
    # Test the function
    comment = get_snarky_comment()
    print(comment)
